services:
  - type: web
    name: maxx-2
    env: static
    rootDir: client
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
